=== 936707967xxy/casc-framework/csas-framework/hs-pdf/src/main/java/com/hoomsun/contract/ftl/pdf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.idawn.org" xmlns="http://www.idawn.org" elementFormDefault="qualified">

	<xs:element name="pdf">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="styles" type="style_type"></xs:element>
				<xs:element name="body" type="body_type"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="style_type">
		<xs:sequence>
			<xs:element name="style" type="style_attribute" maxOccurs="100" />
		</xs:sequence>
	</xs:complexType>

	<xs:attributeGroup name="style_attr_group">
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="pagesize" default="A4">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="A5" />
					<xs:enumeration value="A4" />
					<xs:enumeration value="A3" />
					<xs:enumeration value="A2" />
					<xs:enumeration value="A1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="textalignment" default="LEFT">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="LEFT" />
					<xs:enumeration value="CENTER" />
					<xs:enumeration value="RIGHT" />
					<xs:enumeration value="JUSTIFIED" />
					<xs:enumeration value="JUSTIFIED_ALL" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="fontsize" type="xs:string" />
		<xs:attribute name="bold" default="true">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false" />
					<xs:enumeration value="true" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="height" type="xs:string" />
		<xs:attribute name="width" type="xs:string" />
		<xs:attribute name="margin-top" type="xs:string" />
		<xs:attribute name="margin-right" type="xs:string" />
		<xs:attribute name="margin-bottom" type="xs:string" />
		<xs:attribute name="margin-left" type="xs:string" />
		<xs:attribute name="padding-top" type="xs:string" />
		<xs:attribute name="padding-right" type="xs:string" />
		<xs:attribute name="padding-bottom" type="xs:string" />
		<xs:attribute name="padding-left" type="xs:string" />
		<xs:attribute name="border" type="xs:integer" />
		<xs:attribute name="first-line-indent" type="xs:integer" default="20" />
		<xs:attribute name="under-line" default="false">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false" />
					<xs:enumeration value="true" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>

	<xs:complexType name="style_attribute">
		<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
	</xs:complexType>

	<xs:complexType name="body_type">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<!-- <xs:element name="title" type="comm_type" maxOccurs="1" minOccurs="1" /> -->
			<xs:element name="page" type="page_type" maxOccurs="1000" minOccurs="0" />
		</xs:sequence>
		<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
	</xs:complexType>

	<xs:complexType name="comm_type">
		<xs:attributeGroup ref="comm_attr_group" />
	</xs:complexType>

	<xs:attributeGroup name="comm_attr_group">
		<xs:attribute name="value" type="xs:string"></xs:attribute>
		<xs:attribute name="fill" default="true">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false" />
					<xs:enumeration value="true" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="style" type="xs:string"></xs:attribute>
	</xs:attributeGroup>

	<xs:complexType name="page_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="title" type="comm_type" maxOccurs="1" minOccurs="0" />
			<xs:element name="div" type="div_info" maxOccurs="unbounded" minOccurs="0"></xs:element>
			<xs:element name="table" type="table_info" maxOccurs="unbounded"></xs:element>
			<xs:element name="p" type="p_info" maxOccurs="2000" minOccurs="0"></xs:element>
			<xs:element name="img" type="img_info" maxOccurs="4" minOccurs="0"></xs:element>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="img_info">
		<xs:attribute name="width" type="xs:integer"></xs:attribute>
		<xs:attribute name="height" type="xs:integer"></xs:attribute>
		<xs:attribute name="x" type="xs:integer"></xs:attribute>
		<xs:attribute name="y" type="xs:integer"></xs:attribute>
		<xs:attribute name="offset_x" type="xs:integer"></xs:attribute>
		<xs:attribute name="offset_y" type="xs:integer"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="div_info">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="p" type="p_info" maxOccurs="2000" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="style" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="p_info">
		<xs:choice maxOccurs="2">
			<xs:element name="lable" type="lable_type" maxOccurs="1" minOccurs="0" />
			<xs:element name="span" type="span_type" maxOccurs="1" minOccurs="0" />
		</xs:choice>
		<xs:attribute name="style" type="xs:string"></xs:attribute>
		<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
		<xs:attribute name="fill" default="true">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false" />
					<xs:enumeration value="true" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="foreach" default="true">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false" />
					<xs:enumeration value="true" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="var" type="xs:string"></xs:attribute>
		<xs:attribute name="item" type="xs:string"></xs:attribute>
		<xs:attribute name="varStatus" type="xs:string"></xs:attribute>
		<xs:attribute name="begin" type="xs:string"></xs:attribute>
		<xs:attribute name="end" type="xs:string"></xs:attribute>
		<xs:attribute name="step" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="lable_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="style" type="xs:string"></xs:attribute>
				<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
				<xs:attribute name="fill" default="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="false" />
							<xs:enumeration value="true" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="span_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="style" type="xs:string"></xs:attribute>
				<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
				<xs:attribute name="fill" default="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="false" />
							<xs:enumeration value="true" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="table_info">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="th" type="th_info" maxOccurs="unbounded"></xs:element>
			<xs:element name="td" type="td_info" maxOccurs="unbounded"></xs:element>
		</xs:choice>

		<xs:attribute name="column" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="foreach" default="true">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false" />
					<xs:enumeration value="true" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="var" type="xs:string"></xs:attribute>
		<xs:attribute name="item" type="xs:string"></xs:attribute>
		<xs:attribute name="varStatus" type="xs:string"></xs:attribute>
		<xs:attribute name="begin" type="xs:string"></xs:attribute>
		<xs:attribute name="end" type="xs:string"></xs:attribute>
		<xs:attribute name="step" type="xs:string"></xs:attribute>
		<xs:attribute name="style" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="th_info">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="clm" type="xs:string"></xs:attribute>
				<xs:attribute name="row" type="xs:string"></xs:attribute>
				<xs:attribute name="fill" default="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="false" />
							<xs:enumeration value="true" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="style" type="xs:string"></xs:attribute>
				<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="td_info">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="clm" type="xs:string"></xs:attribute>
				<xs:attribute name="row" type="xs:string"></xs:attribute>
				<xs:attribute name="fill" default="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="false" />
							<xs:enumeration value="true" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="style" type="xs:string"></xs:attribute>
				<xs:attributeGroup ref="style_attr_group"></xs:attributeGroup>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== 936707967xxy/casc-framework/csas-framework/sales-web/src/main/webapp/hxb_model/contract_plan.xml
<?xml version="1.0" encoding="UTF-8"?>
<pdf xmlns="http://www.idawn.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.idawn.org pdf.xsd">
	<styles>
		<style id="title" textalignment="CENTER" fontsize="16" bold="true" />
		<style id="table" fontsize="8" />
		<style id="bold" bold="true" />
		<style id="margin-top-bottom" margin-top="36" margin-bottom="36" />
		<style id="margin-bottom" margin-bottom="36" />
		<style id="margin-top" margin-top="36" />
		<style id="firstLineIndent"  />
		<style id="sign-box"  margin-top="20" textalignment="RIGHT"/>
		<style id="no_border" border="0"/>
		<style id="ce-box"  textalignment="CENTER"/>
	</styles>
	
	<body pagesize="A4" fontsize="10" margin-top="36" margin-right="45" margin-bottom="36" margin-left="45">
		<page>
			<title value="还款管理服务说明书" style="title" />
			<p fill="true"><span>#{custName}先生/女士，您好!</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>1. 还款账户：在《授权扣款委托书》里列示的银行账户是您每次用于还款的账户，请您妥善保管好该银行卡。如发生此银行卡丢失、损坏的情况，请您第一时间联系红上至信商务信息咨询（上海）有限公司（下称“红上公司”），我们将根据具体情况，协助您安排按时还款事宜，以避免不必要的逾期违约金和罚息的产生。如您需变更还款账户，请及时向红上公司提出申请，红上公司相关的工作人员将协助您办理变更还款账户的相关事项。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>2.还款账户最低余额为15元：为了保证您的还款成功扣划，请确保您的还款账户余额在划扣当月还款额后，仍不少于15元。此金额有可能用于支付还款银行的“年费”和其他相关费用。关于此“年费”和其他费用收费标准，请致电您的还款账户开户银行咨询。</span></p>
			<p><span></span></p>
			<p first-line-indent="14" fill="true"><span>3.还款金额：您的每月还款额为RMB #{payMonth}元,请您务必牢记此数字。</span></p>
			<p><span></span></p>
			<p first-line-indent="14" fill="true"><span>4.还款时间：请您在每月#{payDate}日16点之前，将每月还款数额足额存到您的借记卡里，逾期将产生不必要的罚息和违约金，并会影响您的个人信用记录。请您务必记牢还款日，此还款日不因节假日顺延；若当月没有该日期，则还款日为当月最后一天。若您采用跨行转账方式汇入还款账户，请提前一周进行划转。红上公司将以成功划扣还款账户的还款金额时间为准，记录还款时间。如果您申请提前还款或者根据约定您被要求提前还款，则您的还款日期和还款金额按照约定条款确定。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>5.重要提示：红上公司将在第4条规定的还款日期9点至16点之间进行多次划扣，期间划扣成功视为按时还款；至还款日16点后仍扣款失败则视为您还款逾期。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>6.如您因特殊原因暂时无法按时足额还款时，请在当月还款日期之前与红上公司联系。红上公司将协助您安排预约还款并准确告知您还款金额（本息、逾期违约金、罚息、协议约定的相关费用等）。特别需要您注意的是：红上公司有权（代表自身或特定出借人的利益）根据有关协议要求您支付剩余全部借款金额、利息、垫付服务费用、逾期违约金等相关费用。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>7.以下列举如果您在还款第一期即出现不能按时还款且红上公司垫付的情况下，以违约1天和16天为例，您应当支付的垫付服务费用和逾期违约金金额：</span></p>
			<p><span></span></p>
			<table column="3" style="ce-box">
				<th clm="1" row="1">违约天数</th>
				<th clm="1" row="1">垫付服务费用（人民币元）</th>
				<th clm="1" row="1">逾期违约金（人民币元）</th>
				<th clm="1" row="1">1天 </th>
				<th clm="1" row="1"  fill="true">￥#{fOneMoney}</th>
				<th clm="1" row="1"  fill="true">￥#{oveOneMoney}</th>
				<th clm="1" row="1">16天</th>
				<th clm="1" row="1"  fill="true">￥#{fSixteenMoney}</th>
				<th clm="1" row="1"  fill="true">￥#{oveOneMoney}</th>
			</table>
			<p><span></span></p>
			<p first-line-indent="14"><span>8.联系方式变更：为了方便我们更好的服务于您，如果您或是您担保人的联系方式、工作单位、居住或工作地址发生变化，请在第一时间通知红上公司（联系电话：400—602—7111 ）。</span></p>
			<p><span></span></p>
			<p  first-line-indent="14"><span>9.您在红上公司积累了一定的良好信用记录后，比如您已经按时还满一定期数的款项后，如果您有新的借款需求，红上公司会根据您的信用级别、还款情况和还款额提供追加贷的帮助。咨询电话400—602—7111。</span></p>
			<p><span></span></p>
			<p  first-line-indent="14"><span>10.提前一次性还款：为了方便红上公司更好的服务于您，如果您决定于某一还款日提前一次性将全部款项结清，请您务必至少在该还款日前三个营业日前与红上公司相关部门进行沟通，红上公司将帮助您安排预约一次性还款的相关事宜。若因为您提出提前还款的申请时间不满足上述要求，红上公司可能无法为您完成当月提前还款的相关操作，因此带来的利息等损失须由您自身承担。如果发生您应当提前一次性还款的情形，请您在对应的还款日期按照本说明第4条规定进行操作。</span></p>
			<p><span></span></p>
			<p  first-line-indent="14"><span>11.若您有任何问题或金融服务的需求，均可致电红上公司以便获得专业的信用咨询和帮助:咨询电话:400—602—7111。</span></p>
			<p><span></span></p>
			<p  first-line-indent="14"><span>您的还款分期表如下（以下日期为红上公司代为扣款的日期，最终还款日期根据借款协议确定，中间因还款管理操作原因可能存在时间差，您已确认对该等时间差予以接受并同意）：</span></p>
		</page>
		<page>
			<table column="5" foreach="true" var="#{repaymentPlans}" item="plan">
				<th clm="1" row="1">期数</th>
				<th clm="1" row="1">计划还款日</th>
				<th clm="1" row="1">月还款额</th>
				<th clm="1" row="1">尚欠本金</th>
				<th clm="1" row="1">当期一次性还款金额</th>
				<td clm="1" row="1" fill="true">#{plan.shouldTerm}</td>
				<td clm="1" row="1" fill="true">#{plan.shouldDate}</td>
				<td clm="1" row="1" fill="true">#{plan.shouldAmt}</td>
				<td clm="1" row="1" fill="true">#{plan.bal}</td>
				<td clm="1" row="1" fill="true">#{plan.advanceMoney}</td>
			</table>
			<p><span></span></p>
			<p  first-line-indent="14"><span>以上内容由红上公司进行讲解，对于上述内容我已没有疑问。</span></p>
			<p><span></span></p>
			<p><span></span></p>
			<p><span></span></p>
			<table column="1" style="sign-box">
				<th clm="1" row="1" border="0">借款人签字：_________________</th>
				<th clm="1" row="1" border="0">讲解人签字：_________________</th>
				<th clm="1" row="1" border="0">签订日期：______年____月____日</th>
			</table>
		</page>

	</body>
</pdf>

=== 936707967xxy/casc-framework/csas-framework/sales-web/src/main/webapp/hxb_model/contract_jkrsm.xml
<?xml version="1.0" encoding="UTF-8"?>
<pdf xmlns="http://www.idawn.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.idawn.org pdf.xsd">
	<styles>
		<style id="title" textalignment="CENTER" fontsize="16" bold="true" />
		<style id="table" fontsize="8" />
		<style id="bold" bold="true" />
		<style id="margin-top-bottom" margin-top="36" margin-bottom="36" />
		<style id="margin-bottom" margin-bottom="36" />
		<style id="margin-top" margin-top="36" />
		<style id="firstLineIndent"  />
		<style id="sign-box"  margin-top="20" textalignment="RIGHT"/>
		<style id="no_border" border="0"/>
		<style id="ce-box"  textalignment="CENTER"/>
		<style id="le-box"  textalignment="LEFT"/>
	</styles>
	
	<body pagesize="A4" fontsize="10" margin-top="36" margin-right="45" margin-bottom="36" margin-left="45">
		<page>
			<title value="借款人声明" style="title" />
			<p><span></span></p>
			<p first-line-indent="14" fill="true"><span>本人#{custName}，身份证号码：#{idNumber}特此声明如下：</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>本人知悉并同意将与红上至信商务信息咨询（上海）有限公司签署《信用咨询及管理服务协议》以及该等协议之条款内容，并对依据《信用咨询及管理服务协议》自相关出借人处借款并将签署之《借款协议》的全部条款内容知悉并同意，签署该等法律文件均为本人真实意思的表示，未受任何胁迫、误导或欺诈；同时本人承诺：</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>本人无配偶，本人进行前述法律行为无需得到其他主体的同意。（无配偶借款人在空白处抄写此段）</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>本人进行前述法律行为已得到了本人配偶的知晓和同意，本人本次借款系为夫妻共同债务,本人配偶同意以夫妻共同财产偿付本人在前述法律文件项下所负之各项债务。（有配偶的借款人在空白处抄写此段）</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________</span></p>
			<p><span></span></p>
			<p style="le-box"><span>特此声明！</span></p>
			<p><span></span></p>
			<p><span></span></p>
			<p><span></span></p>
			<p><span></span></p>
			<p><span></span></p>
			<table column="1" style="sign-box">
				<th clm="1" row="1" border="0">声明人（签字按手印）：_________________</th>
				<th clm="1" row="1" border="0">日期：______年____月____日</th>
			</table>
		</page>

	</body>
</pdf>

=== 936707967xxy/casc-framework/csas-framework/sales-web/src/main/webapp/model/contract_deductions.xml
<?xml version="1.0" encoding="UTF-8"?>
<pdf xmlns="http://www.idawn.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.idawn.org pdf.xsd">
	<styles>
		<style id="title" textalignment="CENTER" fontsize="16" bold="true" />
		<style id="table" fontsize="8" />
		<style id="bold" bold="true" />
		<style id="margin-top-bottom" margin-top="36" margin-bottom="36" />
		<style id="margin-bottom" margin-bottom="36" />
		<style id="margin-top" margin-top="36" />
		<style id="firstLineIndent"  />
		<style id="sign-box"  margin-top="20" textalignment="RIGHT"/>
		<style id="no_border" border="0"/>
		<style id="center-box" textalignment="CENTER"/>
	</styles>
	
	<body pagesize="A4" fontsize="10" margin-top="36" margin-right="45" margin-bottom="36" margin-left="45">
		<page>
			<title value="委托扣款授权书" style="title" />
			<p><span></span></p>
			<p first-line-indent="14" fill="true"><span>鉴于授权人与红上至信商务信息咨询（上海）有限公司（被授权人）#{year}年#{month}月#{day}日签署的《信用咨询及管理服务协议》（以下简称“合同”），现授权人郑重声明已仔细阅知、理解下述各项规定并同意遵守：</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>一、授权人同意被授权人在合同约定的限期内，委托银行或第三方支付机构从本授权书指定的账户内以约定的资费标准划付应付的费用。授权人同意并确认，银行或第三方支付机构对根据被授权人据此授权进行的上述资金划扣所产生的后果不承担任何责任。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>二、授权人在指定账户中必须留有足够余额，否则因账户余额不足或不可归责于被授权人委托方的任何事由，导致无法及时扣款或扣款错误、失败，责任由授权人自行承担。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>三、合同效力中止或终止后，本授权书效力同时中止或终止，被授权人暂停或终止委托划付款项，待授权人重新与被授权人协商确认继续履行合同后，本授权书效力随即恢复。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>四、本授权书自授权人签字或盖章之日起生效，至授权人书面通知被授权人中止或终止授权、或授权人与被授权人协商确认授权账户终止、或合同效力终止时终止。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>五、授权人拟中止、终止授权或变更账户、通讯地址的，需提前３０个工作日前向被授权人递交书面通知，否则自行承担所造成的风险损失。</span></p>
			<p><span></span></p>
			<p first-line-indent="14"><span>六、授权人保证本授权书的真实性、合法性、有效性，被授权人依据本授权书进行的委托扣款操作引起的一切法律纠纷或风险，由授权人独立承担或解决。</span></p>
			<p first-line-indent="14"><span>七、授权人资料：</span></p>
			<p><span></span></p>
			<table column="2" style="center-box">
				<th clm="1" row="1">银行卡户名</th>
				<td clm="1" row="1" fill="true">#{custName}</td>
				<th clm="1" row="1">银行卡开户银行</th>
				<td clm="1" row="1" fill="true">#{bank}</td>
				<th clm="1" row="1">银行卡账号</th>
				<td clm="1" row="1" fill="true">#{bankNo}</td>
				<th clm="1" row="1">身份证号码</th>
				<td clm="1" row="1" fill="true">#{idNumber}</td>
				<th clm="1" row="1">银行卡预留手机号</th>
				<td clm="1" row="1" fill="true">#{bankPhoneNo}</td>
			</table>
			<table column="1" style="sign-box">
				<th clm="1" row="1" border="0">授权人亲笔签名：_________________</th>
				<th clm="1" row="1" border="0">签订日期：______年____月____日</th>
			</table>
		</page>

	</body>
</pdf>

=== 936707967xxy/casc-framework/csas-framework/sales-web/src/main/webapp/model/contract_two.xml
<?xml version="1.0" encoding="UTF-8"?>
<pdf xmlns="http://www.idawn.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.idawn.org pdf.xsd">
	<styles>
		<style id="title" textalignment="CENTER" fontsize="16" bold="true" />
		<style id="table" fontsize="8" />
		<style id="bold" bold="true" />
		<style id="margin-top-bottom" margin-top="36" margin-bottom="36" />
		<style id="margin-bottom" margin-bottom="36" />
		<style id="margin-top" margin-top="36" />
		<style id="firstLineIndent"  />
		<style id="sign-box"  margin-top="20" textalignment="CENTER"/>
		<style id="conrtact-box" textalignment="RIGHT"/>
		<style id="center-box" textalignment="CENTER"/>
		<style id="left-box" textalignment="LEFT"/>
		<style id="no_border" border="0"/>
	</styles>
	
	<body pagesize="A4" fontsize="10" margin-top="36" margin-right="45" margin-bottom="36" margin-left="45">
		<page>
			<title  value="借款协议" style="title" />
			<p fill="true" style="conrtact-box"><span>协议编号：#{conNo}</span></p>
			<p first-line-indent="14" fill="true"><span>本借款协议（下称“本协议”）由以下双方于#{year}年#{month}月#{day}日在中华人民共和国签署并履行：</span></p>
			<p><span>甲方（借款人及共同借款人）：</span></p>
			<p fill="true"><span>身份证号码：#{idNumber}</span></p>
			<p fill="true"><span>现住址：#{houseAddress}</span></p>
			<p><span>乙方（出借人）：何源</span></p>
			<p><span>身份证号码：513025197101278370</span></p>
			<p><span>地址：西安市莲湖区劳动南路99号锦绣华庭17层6号</span></p>
			<p style="bold"><span>第一条</span></p>
			<p><span>甲方向乙方借款，借款信息如下：</span></p>
			
			<table column="20" style="center-box">
				<th clm="4" row="1">借款详细用途 </th>
				<th clm="6" row="1"></th>
				<th clm="1" row="1">千</th>
				<th clm="1" row="1">百</th>
				<th clm="1" row="1">十</th>
				<th clm="1" row="1">万</th>
				<th clm="1" row="1">千</th>
				<th clm="1" row="1">百</th>
				<th clm="1" row="1">十</th>
				<th clm="1" row="1">元</th>
				<th clm="1" row="1">角</th>
				<th clm="1" row="1">分</th>

				
				<th clm="4" row="1">借款本金数额 </th>
				<th clm="6" row="1" fill="true">人民币（大写）#{conAmount}</th>
				<th clm="1" row="1" fill="true">#{con9}</th>
				<th clm="1" row="1" fill="true">#{con8}</th>
				<th clm="1" row="1" fill="true">#{con7}</th>
				<th clm="1" row="1" fill="true">#{con6}</th>
				<th clm="1" row="1" fill="true">#{con5}</th>
				<th clm="1" row="1" fill="true">#{con4}</th>
				<th clm="1" row="1" fill="true">#{con3}</th>
				<th clm="1" row="1" fill="true">#{con2}</th>
				<th clm="1" row="1" fill="true">#{con1}</th>
				<th clm="1" row="1" fill="true">#{con0}</th>
				
				<th clm="4" row="1">月偿还本息数额</th>
				<th clm="6" row="1" fill="true">人民币（大写）#{shouldAmt}</th>
				<th clm="1" row="1" fill="true">#{amt9}</th>
				<th clm="1" row="1" fill="true">#{amt8}</th>
				<th clm="1" row="1" fill="true">#{amt7}</th>
				<th clm="1" row="1" fill="true">#{amt6}</th>
				<th clm="1" row="1" fill="true">#{amt5}</th>
				<th clm="1" row="1" fill="true">#{amt4}</th>
				<th clm="1" row="1" fill="true">#{amt3}</th>
				<th clm="1" row="1" fill="true">#{amt2}</th>
				<th clm="1" row="1" fill="true">#{amt1}</th>
				<th clm="1" row="1" fill="true">#{amt0}</th>
				
				<th clm="4" row="1">还款分期月数</th>
				<th clm="3" row="1"  fill="true">#{productPeriod}期</th>
				<th clm="2" row="1">还款日</th>
				<th clm="11" row="1"  fill="true">每月 #{payDate} 日（16：00前，节假日不顺延）</th>
				
				<th clm="4" row="1">还款起止日期</th>
				<th clm="16" row="1"  fill="true">#{startTime}起至 #{endTime}止</th>
				
				<th clm="4" row="1">甲方专用账户</th>
				<th clm="1" row="1">户名</th>
				<th clm="2" row="1"  fill="true">#{custName}</th>
				<th clm="1" row="1">账号</th>
				<th clm="4" row="1"  fill="true">#{bankNo}</th>
				<th clm="3" row="1">开户行</th>
				<th clm="5" row="1"  fill="true">#{bank}</th>
			</table>
			
			<p  style="bold"><span>第二条</span></p>
			<p first-line-indent="14"><span>借款本金付款方式：网上银行汇款，由乙方通过网上银行方式将款汇入到本协议第一条约定的甲方专用账号中。若遇到网上银行汇款无法支付的情况下，乙方则通过银行柜台汇款业务将借款汇入到本协议第一条甲方专用账号中。</span></p>
			<p style="bold"><span>第三条</span></p>
			<p first-line-indent="14"><span>甲乙双方对本协议第一条所述借款相关信息全部认可，自主自愿依据本协议第一条规定的内容，由乙方向甲方提供借款。在本协议签署后，经甲方同意及授权乙方将本协议第一条借款本金数额，在扣除代替甲方应交纳给红上至信商务信息咨询（上海）有限公司的咨询费、红上金融信息服务（上海）有限公司审核费及服务费后的剩余款项支付到本协议第一条规定的甲方专用账号中。（咨询费、审核费及服务费的有关事项及具体金额参见甲方与红上至信商务信息咨询（上海）有限公司、红上金融信息服务（上海）有限公司签订的《信用咨询及管理服务协议》）。</span></p>
			<p style="bold"><span>第四条</span></p>
			<p first-line-indent="14"><span>本合同如涉及两人以上借款，任一借款人均应履行本合同项下的义务，对全部借款承担连带清偿责任，乙方有权向任一借款人追索本金利息罚息违约金及其他费用。</span></p>
			<p style="bold"><span>第五条</span></p>
			<p first-line-indent="14"><span>本息偿还方式</span></p>
			<p first-line-indent="14"><span>1）甲方必须按照本协议第一条的规定，按月足额偿还对乙方的借款本金和利息。</span></p>
			<p first-line-indent="14"><span>2）任何应从甲方账户扣划的款项，甲方在此同意乙方委托合作机构每月从甲方指定账户中准确扣划相应数额。</span></p>
			<p first-line-indent="14"><span>3）甲方必须在每月还款日当日（不得迟于16:00）或之前将本协议第一条规定的月偿还本息数额存入本协议第一条规定的甲方专用账号中。</span></p>
			<p first-line-indent="14"><span>4）如果还款日遇到法定假日或公休日，还款日期不进行顺延。</span></p>
			<p first-line-indent="14"><span>5）如果还款日为每月30日，则遇到天数不足30天的月份，还款日为应还款当月的最后一日。</span></p>
		</page>
		<page>	
			<p first-line-indent="14"><span>6）若甲方提前还款，甲方需要至少提前三个工作日提出书面申请，并在甲方和乙方商定的日期当日或之前（非还款日及节假日），由甲方一次性将当月应还款及剩余本金存入本协议第一条规定的甲方专用账号中。</span></p>
			<p style="bold"><span>第六条</span></p>
			<p first-line-indent="14"><span>违约规定</span></p>
			<p first-line-indent="14"><span>6.1若甲方晚于本协议第一条规定的还款日还款，或因甲方原因导致未能在还款日结清当月全部欠款，除应继续按本协议约定履行还款义务外，甲方同意按本条规定向乙方支付罚息和逾期违约金。</span></p>
			<p first-line-indent="14"><span>罚息和逾期违约金计算方法如下：</span></p>
			<p first-line-indent="14"><span>1）逾期违约金：如未按本协议第一条约定的还款时间足额还款，则按照当月应还本息的10%计算，不低于100元，每月单独计算。</span></p>
			<p first-line-indent="14"><span>2）罚息：每日按合同金额的0.05%收取罚息，每月单独计算。</span></p>
			<p first-line-indent="14"><span>3）如因甲方原因导致未能结清当月全部欠款，则按上述第1）、2）项执行。</span></p>
			<p first-line-indent="14"><span>若甲方偿还金额不足，偿还顺序按照先后顺序为罚息、逾期违约金、应还利息、应还本金。</span></p>
			<p first-line-indent="14"><span>6.2如果甲方擅自改变本协议第一条规定的借款用途或严重违反还款义务（包括但不限于逾期达到15天以上），乙方有权提前终止本协议，甲方须在乙方提出终止本协议要求的三日内一次性支付余下的所有本金、利息和逾期违约金。</span></p>
			<p first-line-indent="14"><span>6.3甲方提供虚假资料或者故意隐瞒重要事实，构成违约，应承担违约责任，乙方有权要求解除合同，甲方需要在乙方要求解除合同后三日内一次性支付余下的款项，包括但不限于本金利息罚息违约金及其他费用；构成犯罪的，乙方将有权向相关国家机关报案，追究其刑事责任。</span></p>
			<p first-line-indent="14"><span>6.4乙方保留将甲方违约失信的相关信息在媒体披露的权利。因甲方未还款而带来的调查及诉讼费用将由甲方承担。</span></p>
			<p style="bold"><span>第七条</span></p>
			<p first-line-indent="14"><span>变更通知</span></p>
			<p first-line-indent="14"><span>本协议签订之日起至借款全部清偿之日止，甲方有义务在下列信息变更三日内提供更新后的信息给乙方（包含但不限于）：</span></p>
			<p first-line-indent="14"><span>甲方本人、甲方的家庭联系人及紧急联系人工作单位、居住地址、住所电话、手机号码、电子邮箱的变更。若因甲方不及时提供上述变更信息而带来的乙方的调查及诉讼费用将由甲方承担。</span></p>
			<p style="bold"><span>第八条</span></p>
			<p first-line-indent="14"><span>甲方同意并理解，乙方可以根据自己的意愿进行本协议下其对甲方债权的全部或部分转让，无需通知甲方。在乙方的债权转让后，甲方需对债权受让人继续履行本协议下其对乙方的还款义务，不得以未接到债权转让通知为由拒绝履行还款义务，否则按第六条的规定承担相应责任。</span></p>
			<p style="bold"><span>第九条</span></p>
			<p first-line-indent="14"><span>其他</span></p>
			<p first-line-indent="14"><span>甲方本人、甲方的家庭联系人及紧急联系人工作单位、居住地址、住所电话、手机号码、电子邮箱的变更。若因甲方不及时提供上述变更信息而带来的丙方的调查及诉讼等其他相关费用将由甲方承担。</span></p>
			<p style="bold"><span>第八条 其他</span></p>
			<p first-line-indent="14"><span>1）甲乙双方签订本协议后，本协议于文首所载日期成立；本协议自乙方将本协议第一条所规定的借款本金数额在扣除甲方应支付给红上至信商务信息咨询（上海）有限公司的咨询费、红上金融信息服务（上海）有限公司的审核费及服务费后的剩余款项支付到甲方专用账户之日起生效。甲方将本协议下全部本金、利息、罚息、逾期违约金及其他相关费用全部偿还完毕之日，本协议自动失效。</span></p>
			<p first-line-indent="14"><span>2）本协议及其附件的任何修改、补充均须以书面的形式作出。本协议的补充协议及附件与本协议具有同等的法律效力。</span></p>
			<p first-line-indent="14"><span>3）本协议的传真件、复印件、扫描件等有效复本的效力与本协议原件效力一致。</span></p>
		</page>
		<page>
			<p first-line-indent="14"><span>4）甲乙双方均确认，本协议的签署、生效和履行以不违反中国的法律法规为前提，如果本协议中的任何一条或多条违反适用的法律法规，则该条将被视为无效，但该无效条款并不影响本协议其他条款的效力。</span></p>
			<p first-line-indent="14"><span>5）如果甲乙双方在本协议履行过程中发生任何争议，应友好协商解决，如协议不成，则须提交陕西省西安市未央区人民法院进行诉讼。</span></p>
			<p first-line-indent="14"><span>6）本协议一式叁份，甲方保留壹份，乙方保留贰份。</span></p>
			<p style="conrtact-box"><span>附件一：借款人《还款管理计划书》</span></p>
			<p style="center-box"><span>（以下无正文）</span></p>
			<p><span></span></p>
			<p><span></span></p>
			<p style="left-box"><span>协议各方签字盖章</span></p>
			<p><span></span></p>
			<table column="2">
				<th clm="1" row="1"  border="0">甲方（借款人）：</th>
				<th clm="1" row="1"  border="0">乙方（出借人）：</th>
				<th clm="1" row="1"  border="0">签字：</th>
				<th clm="1" row="1"  border="0">签章：</th>
				<th clm="1" row="1"  border="0">________年______月______日</th>
			</table>
		</page>
	</body>
</pdf>
